[[redirects]]
from = "/atlas/*"
to = "https://cloud-docs.netlify.app/:splat"
status = 200
[[redirects]]
from = "/manual/*"
to = "https://docs-mongodb-internal.netlify.app/:splat"
[[redirects]]
from = "/docs-qa/atlas/*"
to = "http://docs-atlas-dotcomstg.s3-website.us-east-2.amazonaws.com/docs-qa/atlas/:splat"
status = 200
[[redirects]]
from = "/drivers/java/*"
to = "https://docs-java.netlify.app/:splat"
status = 200
[[redirects]]
from = "/drivers/csharp/*"
to = "https://docs-csharp.netlify.app/:splat"
[[redirects]]
from = "/drivers/node/*"
to = "https://docs-node.netlify.app/:splat"
status = 200
[[redirects]]
from = "/drivers/kotlin/*"
to = "https://docs-kotlin.netlify.app/:splat"
status = 200
[[redirects]]
from = "/drivers/php/*"
to = "https://docs-laravel.netlify.app/:splat"
status = 200

[[redirects]]
from = "/drivers/*"
to = "https://docs-ecosystem.netlify.app/:splat"
status = 200
[[redirects]]
from = "/*"
to = "https://docs-landing-mongodb.netlify.app/:splat"
status = 200
