[[redirects]]
from = "/atlas/"
to = "https://cloud-docs.netlify.app/"
status = 200
[[redirects]]
from = "/manual/"
to = "https://docs-mongodb-internal.netlify.app/"
status = 200
[[redirects]]
from = "/"
to = "https://docs-landing-mongodb.netlify.app/"
status = 200
